### ISSUE TITLE
[Epic] Update outdated npm packages

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#1159]
The packages we use for Pulse are pretty outdated. Let's update them!

<img src="https://user-images.githubusercontent.com/2896608/69173903-95fd8680-0ab5-11ea-9987-0a889325ecf0.png" width=420>

- [x] autoprefixer (dependabot PR #1180)
- [x] babel-loader (PR #1183)
- [x] browserslist (PR #1173)
- [x] chokidar (PR #1165)
- [x] chokidar-cli (PR #1165)
- [x] dotenv (issue #1193)
- [x] eslint (PR #1164)
- [x] eslint-config-prettier (PR #1164)
- [x] eslint-plugin-prettier (PR #1164)
- [x] eslint-plugin-react (PR #1164)
- [x] event-stream (issue #1192)
- [x] express (issue #1194)
- [x] helmet (PR #1165)
- [x] mofo-bootstrap (issue #1195)
- [x] mofo-ui (dependabot PR #1185)
- [x] node-sass (issue #1195)
- [x] optipng-bin (PR #1173)
- [x] ~~postcss-cli-simple~~ replaced by postcss-cli (PR #1173)
- [x] qs (issue #1197)
- [x] react (PR #1184)
- [x] react-debounce-input (PR #1175)
- [x] react-dom (PR #1184)
- [x] react-formbuilder (dependabot PR #1168 )
- [x] react-ga (issue #1195)
- [x] react-markdown (PR #1184)
- [x] react-modal (dependabot PR #1169)
- [x] react-router (PR #1182)
- [x] react-router-dom (PR #1182)
- [ ] react-select (issue #1196)
- [x] react-tag-autocomplete (issue #1195)
- [x] shx (dependabot PR #1185)
- [x] stylelint (PR #1164)
- [x] stylelint-config-standard (PR #1164)
- [x] svgo (PR #1164)
- [x] webpack (PR #1165)
- [x] webpack-cli  (PR #1165)

**Comment by alanmoo** [comment]
@mmmavis to convert this to an Epic

**Comment by alanmoo** [comment]
@mmmavis to break into smaller tickets with points (instead of this epic having points) and add them to the milestone/epic

**Comment by mmmavis** [comment]
I'm gonna close this epic since most of the work is done & we have the remaining task filed as its own ticket (update `react-select` #1196)
