### ISSUE TITLE
Pulse at Mozfest [meta]

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#225]
### Kiosk
- [x] Print Pulse signage https://github.com/MozillaFoundation/Mozfest2016_production/issues/198
- [x] Mount Pulse signage
- [x] Reserve computers https://github.com/MozillaFoundation/Mozfest2016_production/issues/199
- [x] Setup kiosk computer https://github.com/mozilla/network-pulse/issues/224
- [x] Kiosk maintenance https://github.com/mozilla/network-pulse/issues/223
- [x] Pick location for kiosk
### Content & Communication
- [ ] Add `Your Name` field to form
- [x] Facilitator orientation (sched etherpads, pulse)
- [x] Enter Science Fair projects #226
- [ ] Screens around building https://github.com/MozillaFoundation/Mozfest2016_production/issues/170
- [x] Comms 
  - https://github.com/MozillaFoundation/Mozfest2016_production/issues/140
  - https://github.com/MozillaFoundation/Mozfest2016_production/issues/144
- [x] Link to Pulse from Mozfest site https://github.com/MozillaFoundation/Mozfest2016_production/issues/200
- [x] Engage with facilitators to capture session outputs 
### MozFest shortlinks
- Submission form – https://mzl.la/mozfest-pulse
- Submission [spreadsheet](https://docs.google.com/spreadsheets/d/1EV-g_e_wx15DQud9_QnwpnWXBbfKyvH3e0CXPF-l3W4/edit#gid=651364736) 
- Shortlink search – https://mzl.la/pulse?keyword=mozfest

**Comment by acabunoc** [comment]
@xmatthewx url to for network mapping:https://network-mapping-app.herokuapp.com/%22

(to point to mzl.la/map)

**Comment by xmatthewx** [comment]
Thanks @acabunoc. Give it a whirl: https://mzl.la/map

**Comment by acabunoc** [comment]
perfect! Thanks @xmatthewx 
cc @liberaliscomputing

**Comment by xmatthewx** [comment]
done and done
