### ISSUE TITLE
Design feature updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#32]
Based on https://github.com/mozilla/network-pulse/issues/5

**Deliverables to incorporate features listed below:**
- [x] Benchmarking 
- [x] Create low-fi mobile comps
- [x] Establish requirements for dev

**Features:**
- [x] Tagging (first need to identify tags https://github.com/mozilla/network-pulse/issues/33)
- [x] Improve featured posts
- [x] Improve starred feature
- [x] Add detail view with deep linking (first need to identify how to divide up content - form ticket https://github.com/mozilla/network-pulse/issues/34)
- [x] Add link share button (dedicated ticket https://github.com/mozilla/network-pulse/issues/18)

**Comment by kristinashu** [comment]
Here are the comps: https://redpen.io/p/by8c797c413d39c620

I'm trying to keep it as clean and simple as possible so we can add features and more personality as it grows.

Added Category Tags (what the tags are can be discussed here https://github.com/mozilla/network-pulse/issues/33).

Moved Featured, Most Recent, My Favorites and Category posts to be 'main menu' options. The side swipe nav might not be obvious in the comps but seems pretty common on other sites/apps but let me know what you think. 

There are a few shared post options.

cc @xmatthewx @mmmavis @hannahkane

**Comment by kristinashu** [comment]
@mmmavis does everything in the comps seem doable this heartbeat (styling, adding categories, adding optional image)?

**Comment by xmatthewx** [comment]
Added a bunch of comments on details. Overall, the design direction is perfect. One significant question is on the detail view and whether external links should live there. 

After next iteration, let's schedule a walk thru with @mmmavis and @acabunoc.

**Comment by kristinashu** [comment]
Thanks for the feedback. Comps are updated (https://redpen.io/p/by8c797c413d39c620) with:
- 'Most Recent' to 'Recent'
- 'My Favorites' to 'Favorites'
- 'Open' to 'View'
- for shared link view, we'll move forward with the nav bar version
- holding off on showing category tags on individual cards https://github.com/mozilla/network-pulse/issues/56
- updated desktop Search icon to pink so it stands out a little more. I think the search bar needs to stay above the nav to be clear it isn't searching within nav items (ex only searching My Favorites...)
- opened a ticket for post MVP work to explore a timeline feature https://github.com/mozilla/network-pulse/issues/55

Things I held off on:
- For long titles, I think we can allow them for now but if it becomes an issue then we can manually edit titles or add a character count.
- Hierarchy of the 4 action buttons on each card. Join over Share? (I like how there is alignment in grouping View and Get Involved together since they are both external whereas Link and Favorite are internal)
- Add detail view: Card includes Fav and “Details”, which opens detail view. Detail view includes External links. Share link could be on card or in detail view. (Still seems more complex than we need right now, I'd prefer to hold off on adding this).

**Comment by xmatthewx** [comment]
This is excellent. Thanks for the summary notes.

> Add detail view

Can we do a quick comp to discuss options for detail view and links? We could make prototype in  codepen or invision mockup and maybe a staff or usertesting.com test, to test the different perceptions of buttons when they're on the card vs in the detail view. 

I am concerned about important info that staff will want to track. For example the Ghanta project has an `Origin` of Unbox Caravan. It's important context, but too much detail for the card. SMS vote updater has roots in an org called Public Knowledge connected to the Ford-Mozilla Open Web Fellows Program. We capture things like this in spreadsheet, but it's not displayed.

**Comment by kristinashu** [comment]
Sounds good, I'll mock it up.

**Comment by kristinashu** [comment]
@xmatthewx the last two screens show the landing page and the detail view, if we had a real detail view page https://redpen.io/p/by8c797c413d39c620

**Comment by kristinashu** [comment]
Opened new ticket for mocking up empty screens https://github.com/mozilla/network-pulse/issues/68

**Comment by kristinashu** [comment]
Few more updates and screens added to redpen https://redpen.io/p/by8c797c413d39c620
- updated 'Favorites' to 'Likes'
- All Categories was the same as Recent so I've just added the category tags to Recent (now there are only 3 menu items!)
- opened a ticket to update the Likes screen to a list instead of cards (post MVP) https://github.com/mozilla/network-pulse/issues/70
- added stress test for names
- added some empty screens #68
Thanks @flukeout and @xmatthewx for the feedback!

**Comment by kristinashu** [comment]
Comps are all updated and dare I say *final*: https://redpen.io/p/by8c797c413d39c620

... well everything except for copy on the empty screens (empty search, empty favs, issues landing, 404) they need a little love.

**Comment by kristinashu** [comment]
Copy has been updated https://redpen.io/p/by8c797c413d39c620
