### ISSUE TITLE
Pulse QA to Triage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#419]
Some notes from testing on Firefox and Chome on Mac and Android.

 * [ ] **Responsive cards** – #491 –  Action: View pulse at different screen widths. Results: cards are squished very thin when they don't need to be. Individual card has tons of margin at browser widths below 992px. On list view, we should switch to 2-per-row below 992px. I recommend a minimum width of something like 340px on list views. 500px on detail view.
 * [ ] **Load more button**  – #427 – Action: Tap "load more" in list view. Scroll down to bottom. Result: Button retains focus/active state from before. Expected: Button returns to default state. `bug`
 * [x] **Search focus** – #425  –  Action: Nav to search view. Expected: Focus should be set to Input
 * [x] **Search clear** – #426  –  Action: Tap X to clear search. Result: Button keeps active state. Expected: Focus should go back into input `bug`
 * [ ] **Search enter** – #492 – Action: On Mobile, hit search/enter key on keyboard. Expected: Keyboard is dismissed.
 * [x] **Tabs reload** – `file issue` – Action: Tap to view a tab. Result: Tabs reloads. Expected: if there's nothing new, tab should display, not reload. 
* [x]  **Loading** – `fixed` – Action: Load a view. Result: It takes a while. Expect: should be snappy to populate first 2 dozen projects (even if images take a bit longer to load) 
 * [x] **List scroll position** – #428 – Action: Go back from an entry to a list view. Result: list reloads. Expected: show me where I was before.
 * [ ] **Web app 404** – #452 – Action: Save Pulse to mobile home screen. Open pulse. Result: 404. Expected: Featured view. Manifest might have wrong url. `bug` 

@kristinashu @mmmavis @alanmoo @Pomax – one person's `bug` is another's `enhancement`. Can I label things that fall in between `features` or something?

**Comment by Pomax** [comment]
Pulse admin
- can you elaborate on the "login to admin"? Because you can't actually log in through the /admin link itself right now =) (which in itself probably needs fixing)
- that sounds like a but that we should file on the api repo
- base django does not have a responsive design, so if we need that for mobile devices, that's a biggie

**Comment by mmmavis** [comment]
@xmatthewx 

> one person's `bug` is another's `enhancement`. Can I label things that fall in between `features` or something?

I'd say if that thing works on v1(https://mozilla.github.io/network-pulse/) but not on `v2` then labels it a `bug`. Otherwise it should be an `enhancement`. `features` label to me sounds more like a big feature that we are going to implement.

**Comment by xmatthewx** [comment]
I moved admin bugs to api repo.

**Comment by xmatthewx** [comment]
@kristinashu – let's discuss & label the list above. then file individual issues.  

@mmmavis – some of these things are more important than an enhancement. We will want to fix the reloading that happens between tabs before a broad audience sees this. I wouldn't call it a bug, but it should be part of 2.1. Or, would you call it a bug?

`Bugs`: Fix in 2.0.1
`In between`: Implement for 2.1. Things required to feel awesome as we share with a broad audience.
`Enhancements`: Consider for a future release. Help wanted. Good first bug.

**Comment by xmatthewx** [comment]
cc @hannahkane

**Comment by hannahkane** [comment]
Perhaps these should be grouped into milestones (2.0.1, 2.1, Beyond) rather than labels?

**Comment by xmatthewx** [comment]
- **Responsive cards** – Action: View pulse at different screen widths. Results: cards are squished very thin when they don't need to be. Individual card has tons of margin at browser widths below 992px. On list view, we should switch to 2-per-row below 992px. I recommend a minimum width of something like 340px on list views. 500px on detail view.

**Comment by mmmavis** [comment]
@xmatthewx 

>`Bugs`: Fix in 2.0.1
`In between`: Implement for 2.1. Things required to feel awesome as we share with a broad audience.
`Enhancements`: Consider for a future release. Help wanted. Good first bug.

@xmatthewx @hannahkane For labels and milestones, can we have **both** category type labels (like bug, enhancement, ... etc) as well as version labels(e.g., v2.1, v3, etc)? If something is a bug... doesn't matter when we want to land the fix the bug is still considered as a bug. If we have both category label and version label we can easily tell the type of the ticket as well as when we are aiming to implement/fix them.

Should we file individual ticket for [each of the items Matthew suggested](https://github.com/mozilla/network-pulse/issues/419#issue-212218068) and label them?

**Comment by hannahkane** [comment]
@mmmavis's labels + milestones plan makes sense to me.

**Comment by xmatthewx** [comment]
I update my list above again. Github or I dropped it before. I gave each item a more clear title. 
To me, these all seem like a v2.0.1. I'm curious if @kristinashu or @hannahkane think anything should be bumped to later. 

@mmmavis – we can start filing individual tickets. But I'm curious what people think about the collection of stuff as a whole.

**Comment by mmmavis** [comment]
> I'm curious if @kristinashu or @hannahkane think anything should be bumped to later.

Hey @xmatthewx what's the timeline we are talking about here?

**Comment by xmatthewx** [comment]
@hannahkane and I will take a look at the upcoming heartbeat today and figure out if this work fits against other priorities. If your plate is clear, you might squash some of the smaller things.

**Comment by Pomax** [comment]
Some small things I ran into that may or may not be worth turning into issues:
- For "latest" it might be good to explicitly say "loading latest results..." instead of just the "..." so that users understand what they're actually looking at/waiting for
- odd quirk in the results: if I (accidentally) click-drag an entry's title to another entry, then the first entry's title stays underlined despite my mouse not being over it anymore.
- the "pulse" in the mozilla pulse logo branding seems a bit thin, and the gap between the two feels a bit off. It would be really neat if using something like `moz://a.pulse` was brand-technically allowed, although that might also make it look like a URL *too* much.
- the default https://www.mozillapulse.org/issues page feels a bit... empty? It feels like we could do more to make people understand what the various issues are and maybe that these are not "issues" in the sense that technical folks might be familiar with.
- https://www.mozillapulse.org/favs might be nice to, when you don't have any favs yet, say "you don't have any favs yet! click here to explore" so that there is a reason for people to click through to the featured list
- perhaps too much work, but clicking on search doesn't actual yield functionality that strictly speaking needs its own page. Instead popping the search bar up in the nav bar without leaving the page the user is on already, only changing content and the url when the user actually types something to search for  might be nicer.

**Comment by kristinashu** [comment]
Here's a link to our prioritization etherpad https://public.etherpad-mozilla.org/p/pulse-qa-triage

**Comment by xmatthewx** [comment]
Closing. I believe this all done or filed elsewhere. Reopen if I'm mistaken.
