### ISSUE TITLE
Iterate prototype to prep for org-wide testing

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#5]
### Proposed deliverables for July 11-22 heartbeat

- [x] **Deliverable: Small slide deck that... (https://github.com/mozilla/network-pulse/issues/23)**
 - Synthesizes and simplifies the research and recommendations in [this doc](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.g9fpre8yvc04).
 - Proposes an H2 roadmap (e.g. UX iteration w/ Issue integration; Program process plan for input; Mozfest kiosk test; EOY review, report and recommendations)
 - Goal: Make it easy to communicate with all staff this project’s what, why, when, and how (big picture, 6-10 slides)
<br></br>

- [x] **Deliverable: 2-3 sets of wireframe options that integrate features listed below (https://github.com/mozilla/network-pulse/issues/32)** 
 - Should be mobile-first
 - Should be an app/dashboard, not a website
 - Primary audience/user is staff. Secondary is lead network members (fellows, mozfest facilitators, hive org members, etc)
 - Shouldn’t shy away from [bold design](https://docs.google.com/presentation/d/10QvAb_utE6KXgIucuQiJ65NW3frmq85XTBgo76r_AvY/edit#slide=id.g10b63240b1_0_37)
 - Shouldn’t introduce complexity or make input more difficult (e.g. require an image)
 - Goal: Establish requirements for UI design and dev implementation. 
<br></br>

**Deliverable: Code iteration (https://github.com/mozilla/network-pulse/issues/9)**
- [x] Review and clean up code (https://github.com/mozilla/network-pulse/issues/16)
- [x] Migrate instance to github.com/mozilla/NetworkPulse (https://github.com/mozilla/network-pulse/issues/8)
- [x] Prep plumbing for new features (design pending) 
- [x] Detail view (follow pattern on http://mozilla.github.io/clubs-events/)
- [x] Deep-linking (https://github.com/mozilla/network-pulse/issues/15)
- [x] Share button (Copy URL, Twitter, Email)

### Features

- [x] **Issues & tags** – Integrate tags/issues and refine how people/projects/issues show up as key navigational and sense-making elements.
- [x] **Tabs** – Navigate between Projects, Stories, Signals (articles, external projects) 
- [x] **Featured** – Give prominence to curated exemplar work or stories. How does the stream feed our story?
- [x] **Detail view** – Tap summary to view full set of links, descriptions, tags, etc (See pattern in http://mozilla.github.io/clubs-events/) (https://github.com/mozilla/network-pulse/issues/14)
- [x] **Share button** – Copy link, share via email, twitter (https://github.com/mozilla/network-pulse/issues/19 and https://github.com/mozilla/network-pulse/issues/18)

cc @hannahkane @kristinashu

**Comment by xmatthewx** [comment]
[Research doc](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.g9fpre8yvc04) with statement of problem and opportunity and notes from interviews with various staff

**Comment by mmmavis** [comment]
Hey @xmatthewx since you are on PTO and we don't have collaborator rights on your personal repo, we have forked your repo and filed a ticket (with "Leaders -> Leaders" label applied) [here](https://github.com/mozilla/network-pulse/issues/1) instead.

**Comment by xmatthewx** [comment]
Yay. This issue was missing [a doc link](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.g9fpre8yvc04) in the first bullet that outlines the problem and opportunity. Might explain the kickoff confusion. Copy-pasta 🍝

**Comment by kristinashu** [comment]
@xmatthewx I think it would be great to get the small slide deck mentioned above done before doing the other deliverables - I'm still a little confused. Is someone working on this?

**Comment by xmatthewx** [comment]
@kristinashu – cool. you and I can start drafting while we meet today.

**Comment by kristinashu** [comment]
I've updated this ticket with check boxes, linked associated tickets, and converted this ticket into an Epic.

**Comment by kristinashu** [comment]
Woot! I think we've done some version of all of these and are now going above and beyond!
