### ISSUE TITLE
Add tags to connect projects

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#500]
Tags are awesome. The help users find related things. 

Already implemented
 - request and accept tags on submission
 - offer route to view projects by tag (e.g. [mozfest](https://www.mozillapulse.org/tags/mozfest)) 
 
Assumption: We should probably display issue categories and tags. For users, a single visual treatment is probably best. 

To do 
 - [x] design display of tag links on cards `Estimation: 3` If tags are at bottom of card, design is pre-approved. R+. 
 - [ ] #523 add tags to frontend to leverage api
 - [ ] #482 add autocomplete to Add-New form `Estimation: 8`
 - [ ] #525 clean up existing tags to fix typos and merge similar (game/games) `Estimation: 5`

**Comment by kristinashu** [comment]
Tags should appear on detail view like so: 

![desktop - detail -tags 2x](https://cloud.githubusercontent.com/assets/1068783/25597226/73125342-2e82-11e7-861c-12b93d0c602d.png)

**Comment by kristinashu** [comment]
Tag results are already built in #56 https://www.mozillapulse.org/tags/mozfest

**Comment by kristinashu** [comment]
Added some autocomplete suggestions in #482

**Comment by xmatthewx** [comment]
I think we need a ticket for specifically for design and implementation of adding tags to project cards. 

@kristinashu I really like your tag style on the newer get involved design. Button/box rather than link. 

Some projects have a lot of tags. And the metadata feels a little funny in the middle, before the primary action button. Could we try it as a card footer? Fifty entries and have 6 TO 9 tags.

**Comment by xmatthewx** [comment]
closing this meta ticket. tracking the work in individual tickets.
