### ISSUE TITLE
Add Moderation to open submissions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#501]
Moderation is a pre-requisite to opening the platform to a bunch of network members. 

Assumptions: 
 - MVP moderation is a single toggle in DB between: needs moderation, approved, declined. 
 - Existing API routes will need to be updated
 - Posts by users flagged is_staff should default to approved

 - [ ] setup data model with new field
 - [ ] update existing api
 - [ ] design and implement clarification on submission form (confirmation message/redirect to staff and users might be different)

**Comment by alanmoo** [comment]
Moderation is enabled on staging, check it out and try logging in with your non-Mozilla email. https://network-pulse-staging.herokuapp.com/

**Comment by hannahkane** [comment]
Exciting to see this happening! The ticket describes three states - needs moderation, approved, declined, but I only see an "Is Approved" checkbox. Am I missing something, or did the requirements change?

**Comment by alanmoo** [comment]
It was extremely simple to implement as a Boolean to get to MVP status and I checked with Matthew, he said that was reasonable. Apologies for not updating the ticket. I suppose we could make it a select field, but off the top of my head I can't think of the effort/other things that might need changing. @pomax what do you think?

**Comment by Pomax** [comment]
I would keep things simple: there is not a lot of utility in "declining" a submission but then keeping it around in the db, If an entry does not meet with our approval we can simply deleted them, instead. Any entry with "is_approved" not set is then by default "pending moderation", any entry with "is_approved" set is an accepted entry, and any entry that's been deleted is... well it's gone, it no longer plays a role =)

**Comment by hannahkane** [comment]
I think the potential utility comes in when we consider that there will likely be multiple reviewers, so there are some workflow issues. Maybe, at some point, we'll want to be able to search for entries with is_approved not set. That way one reviewer will be able to easily see where another reviewer stopped in the queue, or if they accidentally or purposefully skipped any.

Not suggesting we do this now; I think we can wait and see if any actual needs emerge. My comment above was just making sure that stakeholders were aware of the discrepancy between the original ticket and what was implemented. Sounds like everyone's aware/cool with it, so no changes needed.

**Comment by Pomax** [comment]
that feels already adressed by deleting unwanted entries. If a reviewer hits up "all not-is_approved entries" then they will see exactly the set of entries not yet reviewed by anyone else.

**Comment by hannahkane** [comment]
How do I filter by not-is_approved?

**Comment by Pomax** [comment]
right now, you don't, but we can make that a thing that you can do in the admin view

**Comment by hannahkane** [comment]
got it. That's what I was suggesting in my comment above.

**Comment by xmatthewx** [comment]
A checkbox is fine to land this. We'll need to add a few options for state in the near future. 

I'm a bit out of the loop, so I'm unsure if I should close this and open something new. Looks like  moderation is merged. >>> Please comment or triage if you have enough info.

Moderation states: 
 - `Pending` (or needs review)
 - `Approved`
 - `Declined` (with many moderators, saving data will prevent whoopsies. also allows us to see and address a user who has many things declined)
 - `In Review` (staff or mentor could request a rewrite or more info from submitter, and avoid another moderation hitting approved or declined. we can ask moderators to use the existing internal notes field to complement this)

**Comment by hannahkane** [comment]
@xmatthewx - I'm going to file your enhancement as a follow-up ticket, and close this one, to avoid super long threads. :)
