### ISSUE TITLE
Prep Pulse for MozFest

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#710]
We should do some things, such as...

### kiosk & signage
 - [x] request a kiosk
 - [x] design a sign for the kiosk (like last year) https://github.com/MozillaFoundation/mozfest-design-2017/issues/63
 - [x] #726 design and print a simple small poster to advertise stuff. printing for Ravensbourne and House: https://github.com/MozillaFoundation/mozfest-design-2017/issues/78
 - [x] motion graphics loop (typo)

### activities
 - [ ] maybe plan informal data viz session
 - [ ] maybe plan informal pulse-a-thon
 - [x] #738 prep user research 
 - [x] #748 prepare for pace of moderation

### integration
 - [x] [ Zannah ] include pulse in facilitators guide
 - [x] [ Sabrina ] include pulse in guide and on badge
 - [x] [ Esme ] make sure science fair participants are encouraged to post their stuff pre-festival
 - [ ] [ Esme ?? ] remind closing demo participants to post stuff
 - [x] [ Kevin, Aliza, Kristina G, Temi ] connect with comms to monitor pulse for stories, link to pulse/site in blog posts (rather than final destination)
 - [ ] [ Erika ?? ] include pulse in welcome speech and facilitator orientation 

Anything else? cc @kristinashu

**Comment by xmatthewx** [comment]
Hey ya @edrushka – I'm doing some MozFest prep, to integrate Pulse. See checklist above. I'm curious: who are the best people for me to connect with regarding Sci Fair? And is one person leading the Comms?

**Comment by edrushka** [comment]
Contact Esme for Science Fair. Kevin for press. Aliza for blogs. Kristina Gorr for pre-festival social. Temi for live festival social.

**Comment by xmatthewx** [comment]
done! closing.
