### ISSUE TITLE
Associate and clean up existing Creators

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#775]
Pulse has existing Users with Profiles that we want to associate with existing Creators. 

I dug through the DB, and prepped a spreadsheet. Notes on the tabs...

### Part 1 
 - [x] **associate**: matching names. note: a few names match multiple users. i de-duped them. this list is clean and only includes preferred match. 
 - [x] **associate 2**: a few names matched, but strings differed slightly. 
 - [x] **dedupe creator**: a few creators had duplicate entries, including Mozilla. we should at least merge Mozilla.  

### Part 2
 - [ ] **split**: some creators need to be split 
(e.g. `id: 225; name: "Bill Day, Jon Bruner, Aurelia Moser"`)

### Part 3
 - [ ] **yuck**: this tab is a bucket of mess. items need to be manually fixed. or ignored!
 - **user x2**: these are staff with multiple accounts. no action needed.

**Comment by gideonthomas** [comment]
For Part 2, split, the only item that has been split is "Coral/Mozilla"

**Comment by xmatthewx** [comment]
Great. Thanks. Let's call this done. We can clean up other bits manually if and when people ask for it.
