### ISSUE TITLE
Prep Pulse for partner and contributors

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#830]
Issues to file:
 - [x] recap use at MozFest and user research
 - [x] improve developer ergonomics
 - [x] improve contributor docs & readme & about entry (#889)
 - [x] set up API versioning
 - [x] plan reward and recognition of contributors (callout on pulse profile) (#890)
 - [ ] identify meaty, non-critical path features for CDOT and other contributors

**Comment by xmatthewx** [comment]
@alanmoo - following today's conversation, list at top of this epic is worth a look.

**Comment by alanmoo** [comment]
I've created issues for two of these to spin off their own conversations, but I don't understand the plans for the last bullets well enough to be able to generate a ticket.

**Comment by xmatthewx** [comment]
Hmm. Well, maybe we schedule a conversation with a few of us and humph after all hands or in early January to discuss?

**Comment by alanmoo** [comment]
Sure, though I mean I don't understand the features you're describing. If we can flesh those out more clearly, we can create issues to get help with them.

**Comment by xmatthewx** [comment]
oh. those were just thoughts while we met, before we even did the prioritization. i'll remove 'em.

**Comment by alanmoo** [comment]
@xmatthewx The remaining item seems very vague at this point. Can we close this? Unassigning myself.

**Comment by xmatthewx** [comment]
closing
