### ISSUE TITLE
Enhance search

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#861]
Search is awesome. Let's enhance it to: 
 - include people names in query (still returns a list of entries, not profiles)
   - [ ] (https://github.com/mozilla/network-pulse-api/issues/260) API ... squash bug, switch it on, or build it out
 - show a persistent search box (helps reveal pulse's power as an archive)
   - [ ] [#841] Design: Figure out nav dependencies. Create comp for mobile. (Note: this takes up header real estate. Hopefully we can identify and clear the minimal dependencies to unblock this.)
   - [ ] [to file] Frontend: Build it out. Figure out state transition with designer. 

![image](https://user-images.githubusercontent.com/53411/33092314-d110e32e-cec7-11e7-8e1c-7242ca74f3f8.png)

**Comment by mmmavis** [comment]
@xmatthewx if we are moving nav links away from nav bar I would like to have mockups for every type of pages on Pulse as well as their mobile version (if the page nav links will be positioned and styled differently on different views).

**Comment by xmatthewx** [comment]
Yep. Totally. We have some things to sort out design wise before this build can begin.

**Comment by Pomax** [comment]
After analysis of the effect on system performance, it turns out we can't actually add people as a search set to the standard search without bringing the system down to its knees, so we might need to rethink our needs here:

- what are we trying to offer people here
- can we find the most important metadata that should always be included in a search
- can we split any metadata off to have its own UI (for instance, tags?)
- can we offer UI to effect different searches? (for instance, an amazon style 'drop down' to pick which thing you're searching in, or a flicker style "advanced search" page on which you can actually fill in every possible metadata field you need to filter in?)

We've effectively hit the limit of search unless we want to get our hands particularly dirty to hand-craft the searching rather than leaving it to Django itself.

**Comment by xmatthewx** [comment]
Okay. Thanks for the investigation. We'll discuss design-wise before we proceed with anything else.

**Comment by alanmoo** [comment]
@Pomax my understanding of this is that a lot of the complication comes from the ordered nature of the creators list causing an intermediate layer we need to navigate through. What if we were to simply do 2 searches- one for entries like we normally do, don't look at creators. Then a second one where we search the set of creators and pull in entries related to them. Would that not be a lesser magnitude of search than trying to find the creators within the entries?

**Comment by Pomax** [comment]
In this case "simply" actually translates to "figure out how to bypass DRF's built in search and shim it ourselves to do multiple searches and multiple set resolutions to remove duplicates, then build a paginated result set manually", which I have reservations about. in terms of maintainabilty and upgrade-proofing.

So with that said, many sites I use split the "search everything we have" functionality up into "only search basic metadata" plus some advanced search filter in case you need more, where the advanced search by its very nature is allowed to take longer as it meets the user's expectation of requiring more work to resolve.

In this case, it feels worth shaping user expectation through good UI rather than to try to bypass DRF's way of automatically searching and filtering.

**Comment by xmatthewx** [comment]
Discussing technical options in a [gdoc](https://docs.google.com/document/d/1_eNxhsWMaWQSg_lZZuQI_04vlXGsFNIRZlFPeixjD9M/edit#).

**Comment by xmatthewx** [comment]
Closing. Tracking a new potential solution in [Project 4](https://github.com/mozilla/network-pulse/projects/4) in this repo.
