### ISSUE TITLE
Code iteration

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#9]
#Extracted from https://github.com/xmatthewx/network-pulse/issues/5

---

Deliverable: Code iteration
 - [x] Review and clean up code (filed as issue https://github.com/mozilla/network-pulse/issues/16)
 - [x] Migrate instance to github.com/mozilla/NetworkPulse (filed as issue https://github.com/xmatthewx/network-pulse/issues/5)
 - Prep plumbing for new features (design pending) 
  - [x] Detail view (follow pattern on http://mozilla.github.io/clubs-events/) (filed as issue https://github.com/mozilla/network-pulse/issues/14)
  - [x] Deep-linking (filed as issue https://github.com/mozilla/network-pulse/issues/15)
  - [ ] Share button (Copy URL, Twitter, Email)

**Comment by mmmavis** [comment]
@xmatthewx mind elaborating on the "share button" part? 😺

**Comment by xmatthewx** [comment]
I've filed #19 to clarify and discuss. There's a bit of a chicken-egg tech-design situation.

**Comment by xmatthewx** [comment]
Seems like we could close this and track other bits in their specific issues. True? False?

**Comment by mmmavis** [comment]
Yup yup let's do that!
